### ISSUE TITLE
Please set the target to build.

### ISSUE THREAD

**Issue by cedricbahirwe** [elegantchaos/atom-ide-swift#23]
This is the message I got when I try to run the "Swift" code to the console!!! What is happening!
I've already installed all the packages

**Comment by tanvirgeek** [comment]
I am having same problem. Any clue?

**Comment by CyberPunk87** [comment]
likewise.

**Comment by cedricbahirwe** [comment]
Looks like it's not being maintained anymore so no help can be provided ...
